# Generated by Django 5.0.2 on 2024-03-01 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('SF', 'Safaricom'), ('BK', 'Bank')], max_length=20)),
                ('safaricom_service', models.CharField(choices=[('PC', 'Pochi La Biashara'), ('BG', 'Buy Goods'), ('PB', 'Pay Bill')], max_length=20)),
                ('more', models.CharField(max_length=50)),
                ('fee_structure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice.feestructure')),
                ('payment_slip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentform')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
