# Generated by Django 5.0.2 on 2024-03-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
